import 'package:flutter/material.dart';

enum Keys {
  a0,
  a1,
  a2,
  a3,
  a4,
  a5,
  a6,
  a7,
  a8,
  a9,
  q,
  w,
  e,
  r,
  t,
  y,
  u,
  i,
  o,
  p,
  a,
  s,
  d,
  f,
  g,
  h,
  j,
  k,
  l,
  z,
  x,
  c,
  v,
  b,
  n,
  m,
  exclamation,
  at,
  hash,
  dollar,
  percent,
  caret,
  ampersand,
  asterisk,
  pOpen,
  pClose,
  Q,
  W,
  E,
  R,
  T,
  Y,
  U,
  I,
  O,
  P,
  A,
  S,
  D,
  F,
  G,
  H,
  J,
  K,
  L,
  Z,
  X,
  C,
  V,
  B,
  N,
  M,
  backspace,
  next,
  shift,
  spacebar,
  dot
}

String getKeysChar(Keys key) {
  return switch (key) {
    Keys.a0 => "0",
    Keys.a1 => "1",
    Keys.a2 => "2",
    Keys.a3 => "3",
    Keys.a4 => "4",
    Keys.a5 => "5",
    Keys.a6 => "6",
    Keys.a7 => "7",
    Keys.a8 => "8",
    Keys.a9 => "9",
    Keys.q => 'q',
    Keys.w => 'w',
    Keys.e => 'e',
    Keys.r => 'r',
    Keys.t => 't',
    Keys.y => 'y',
    Keys.u => 'u',
    Keys.i => 'i',
    Keys.o => 'o',
    Keys.p => 'p',
    Keys.a => 'a',
    Keys.s => 's',
    Keys.d => 'd',
    Keys.f => 'f',
    Keys.g => 'g',
    Keys.h => 'h',
    Keys.j => 'j',
    Keys.k => 'k',
    Keys.l => 'l',
    Keys.z => 'z',
    Keys.x => 'x',
    Keys.c => 'c',
    Keys.v => 'v',
    Keys.b => 'b',
    Keys.n => 'n',
    Keys.m => 'm',
    Keys.exclamation => '!',
    Keys.at => '@',
    Keys.hash => '#',
    Keys.dollar => r'$',
    Keys.percent => '%',
    Keys.caret => '^',
    Keys.ampersand => '&',
    Keys.asterisk => '*',
    Keys.pOpen => '(',
    Keys.pClose => ')',
    Keys.Q => 'Q',
    Keys.W => 'W',
    Keys.E => 'E',
    Keys.R => 'R',
    Keys.T => 'T',
    Keys.Y => 'Y',
    Keys.U => 'U',
    Keys.I => 'I',
    Keys.O => 'O',
    Keys.P => 'P',
    Keys.A => 'A',
    Keys.S => 'S',
    Keys.D => 'D',
    Keys.F => 'F',
    Keys.G => 'G',
    Keys.H => 'H',
    Keys.J => 'J',
    Keys.K => 'K',
    Keys.L => 'L',
    Keys.Z => 'Z',
    Keys.X => 'X',
    Keys.C => 'C',
    Keys.V => 'V',
    Keys.B => 'B',
    Keys.N => 'N',
    Keys.M => 'M',
    Keys.spacebar => ' ',
    Keys.backspace => '',
    Keys.next => '',
    Keys.shift => '',
    Keys.dot => '.',
  };
}

Widget getKeyWidgetPinPad(Keys key) {
  return switch (key) {
    Keys.a0 ||
    Keys.a1 ||
    Keys.a2 ||
    Keys.a3 ||
    Keys.a4 ||
    Keys.a5 ||
    Keys.a6 ||
    Keys.a7 ||
    Keys.a8 ||
    Keys.a9 ||
    Keys.a0 ||
    Keys.dot =>
      Text(getKeysChar(key),
          style: const TextStyle(
            fontSize: 32,
            fontWeight: FontWeight.w400,
          )),
    Keys.backspace => const Icon(Icons.backspace),
    Keys.next => const Icon(Icons.check),
    _ => Container(),
  };
}

Widget getKeyWidgetKeyboard(Keys key, Color? color) {
  return SizedBox(
    height: 32,
    child: switch (key) {
      Keys.backspace => Icon(Icons.backspace, color: color),
      Keys.next => Icon(Icons.check, color: color),
      Keys.shift => Icon(Icons.format_size, color: color),
      Keys.spacebar => Text(
          '_____________________',
          style: TextStyle(
            fontSize: 28,
            fontWeight: FontWeight.w100,
            color: color,
          ),
        ),
      _ => Text(
          getKeysChar(key),
          style: TextStyle(
            fontSize: 28,
            fontWeight: FontWeight.w400,
            color: color,
          ),
        ),
    },
  );
}
