name: xmruw
description: "monero wallet for android."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+100

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  qr_flutter: 4.1.0
  ffi: ^2.1.0
  path_provider: 2.1.1
  mutex: 3.1.0
  monero:
    git: 
      url: https://github.com/mrcyjanek/monero.dart
      ref: 7b301d37215c79059ccf3b7aefddc3842d4ef9d4
  cr_file_saver: 0.0.2
  file_picker: 6.1.1
  mobile_scanner: 4.0.1
  anonero_backup:
    git:
      url: https://github.com/MrCyjaneK/anonero_backup
      ref: 0bcca6597c5887a4ed7f402a3d1d2cc92eed50f5
  flutter_svg: 2.0.10+1
  archive: 3.4.10
  tor_binary:
    git:
      url: https://github.com/MrCyjaneK/flutter-tor_binary
      ref: da00d4f4c3918e78734bbe0e9496559fc342d8b5
  disable_battery_optimization: ^1.1.1
  flutter_background_service: 5.0.5
  flutter_background_service_android: 6.2.2
  flutter_local_notifications: 16.3.3
  permission_handler: 11.1.0
  libstealth_calculator:
    git:
      url: https://github.com/MrCyjaneK/libstealth_calculator
      ref: fafdb3d215dbc09f1901062cb1c43bfcac374844
  path: any
  flex_color_picker: 3.3.1
  polyseed: 0.0.4
  introduction_screen: 3.1.14
  http: 1.2.1


dev_dependencies:
  flutter_test: 
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"
  flutter_oss_licenses: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
  # macos:
  #   generate: true
  #   image_path: "assets/anon_logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/logo_calc.png
    - assets/fonts/RobotoMono.ttf
    - assets/scanner_frame.svg
    - assets/nodes.txt
    - assets/changelog.jsonp
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
