name: xmruw
description: "monero wallet for android."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

# When adding a dependency from git, if it is from trusted source, use
# branch as ref, if it is questionable source - as in somebody else than
# me, then pin via hash

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  intl: 0.19.0
  qr_flutter: 4.1.0
  ffi: 2.1.3
  path_provider: 2.1.4
  mutex: 3.1.0
  monero:
    git:
      url: https://github.com/mrcyjanek/monero_c
      ref: 3cb38bee9385faf46b03fd73aab85f3ac4115bf7 # monero_c hash
      path: impls/monero.dart
  cr_file_saver:
    git:
      url: https://github.com/crit-iq/cr_file_saver
      ref: 1db62fd53adf9b34d4b769788d6c4be4fa416817
  file_picker: 8.0.6
  win32: 5.5.4 # Remove this after file_picker update
  fast_scanner:
    git:
      url: https://github.com/mrcyjanek/fast_scanner
      ref: a72bd80f5f095f105a64c850d7a056c780505bbc
  anonero_backup:
    git:
      url: https://github.com/MrCyjaneK/anonero_backup
      ref: 90c1586e2a43cb8d26627244cf53f2281b520f0d
  flutter_svg: 2.0.10+1
  archive: 3.6.1
  tor_binary:
    git:
      url: https://github.com/MrCyjaneK/flutter-tor_binary
      ref: adfd6e0bcfa794d8716f799b150b49067e9eb94f
  disable_battery_optimization: 1.1.1
  permission_handler: 11.3.1
  libstealth_calculator:
    git:
      url: https://github.com/MrCyjaneK/libstealth_calculator
      ref: 2cb96d476e99a795ce5960787444a96c44d4ccc8
  path: any
  flex_color_picker: 3.5.1
  polyseed: 0.0.6
  introduction_screen: 3.1.14
  http: 1.2.2
  device_preview: 1.2.0


dev_dependencies:
  flutter_test: 
    sdk: flutter

  flutter_lints: 4.0.0
  flutter_launcher_icons: 0.13.1
  flutter_oss_licenses: 3.0.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_calc.png
    - assets/fonts/RobotoMono.ttf
    - assets/scanner_frame.svg
    - assets/nodes.txt
    - assets/changelog.jsonp

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono.ttf
