name: xmruw
description: "monero wallet for android."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  intl: 0.19.0
  qr_flutter: 4.1.0
  ffi: 2.1.2
  path_provider: 2.1.3
  mutex: 3.1.0
  monero:
    git:
      url: https://github.com/mrcyjanek/monero.dart
      ref: 7b301d37215c79059ccf3b7aefddc3842d4ef9d4
  cr_file_saver:
    git:
      url: https://github.com/crit-iq/cr_file_saver
      ref: 1db62fd53adf9b34d4b769788d6c4be4fa416817
  file_picker: 8.0.5
  win32: 5.5.1 # Remove this after file_picker update
  mobile_scanner: 5.1.1
  anonero_backup:
    git:
      url: https://github.com/MrCyjaneK/anonero_backup
      ref: 0bcca6597c5887a4ed7f402a3d1d2cc92eed50f5
  flutter_svg: 2.0.10+1
  archive: 3.6.1
  tor_binary:
    git:
      url: https://github.com/MrCyjaneK/flutter-tor_binary
      ref: da00d4f4c3918e78734bbe0e9496559fc342d8b5
  disable_battery_optimization: ^1.1.1
  permission_handler: 11.3.1
  libstealth_calculator:
    git:
      url: https://github.com/MrCyjaneK/libstealth_calculator
      ref: fafdb3d215dbc09f1901062cb1c43bfcac374844
  path: any
  flex_color_picker: 3.5.1
  polyseed: 0.0.5
  introduction_screen: 3.1.14
  http: 1.2.1
  device_preview: 1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 4.0.0
  flutter_launcher_icons: 0.13.1
  flutter_oss_licenses: 3.0.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter:
  assets:
    - assets/logo.png
    - assets/logo_calc.png
    - assets/fonts/RobotoMono.ttf
    - assets/scanner_frame.svg
    - assets/nodes.txt
    - assets/changelog.jsonp

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono.ttf
