name: Android Release
run-name: Building Anonero for android
on: 
  push:
    tags:
      - '*'

jobs:
  android-apk-release:
    runs-on: androidsdk-flutter
    steps:
      # - name: Prepare F-droid repo
      #   run: |
      #     mkdir /fdroidrepo \
      #     && fdroid init
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Flutter pub get
        run: |
          cd ${{ gitea.workspace }} \
          && flutter pub get
      - name: Build apk
        run: |
          cd ${{ gitea.workspace }} \
          && flutter build apk --no-tree-shake-icons
      - name: Create release
        uses: akkuman/gitea-release-action@v1
        with:
          body: |
            This is a **preview** release to be used by testers.
            It was build from **${{ gitea.ref }}** commit `${{ gitea.sha }}`
            ### Release info
            ${{ github.event.head_commit.message }}
          #name: "${{ gitea.reg_name }}-${{ gitea.sha }}"
          #tagname: "${{ gitea.reg_name }}-${{ gitea.sha }}"
          files: |-
            ${{ gitea.workspace }}/build/app/outputs/flutter-apk/app-release.apk