name: Android Release
run-name: Building Anonero for android
on: 
  push:
    tags:
      - '*'

jobs:
  android-apk-release:
    runs-on: androidsdk-flutter
    steps:
      # - name: Prepare F-droid repo
      #   run: |
      #     mkdir /fdroidrepo \
      #     && fdroid init
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Flutter pub get
        run: |
          cd ${{ gitea.workspace }} \
          && flutter pub get
      - name: make version
        run: |
          cd ${{ gitea.workspace }} \
          && make version
      - name: Build apk
        continue-on-error: false
        run: |
          cd ${{ gitea.workspace }} \
          && make apk
      - name: Build linux (debian)
        continue-on-error: true
        run: |
          cd ${{ gitea.workspace }} \
          && make deb \
          && curl --user mrcyjanek:$PAT_SECRET_PACKAGE \
          --upload-file build/linux/x64/release/debian/*.deb \
          https://git.mrcyjanek.net/api/packages/mrcyjanek/debian/pool/no-distro/main/upload
      - name: Build linux (tarball)
        continue-on-error: true
        run: |
          cd ${{ gitea.workspace }} \
          && make linux
      - name: Create release
        uses: akkuman/gitea-release-action@v1
        with:
          body: |
            This is a **preview** release to be used by testers.
            It was build from **${{ gitea.ref }}** commit `${{ gitea.sha }}`

            ### Release info
            ${{ github.event.head_commit.message }}
          #name: "${{ gitea.reg_name }}-${{ gitea.sha }}"
          #tagname: "${{ gitea.reg_name }}-${{ gitea.sha }}"
          files: |-
            ${{ gitea.workspace }}/build/app/outputs/flutter-apk/app-anon-release.apk
            ${{ gitea.workspace }}/build/app/outputs/flutter-apk/app-nero-release.apk
            ${{ gitea.workspace }}/build/linux/x64/release/anonero-linux-amd64.tar.xz