clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false

matrix:
  include:
    - image: ghcr.io/cirruslabs/flutter:3.19.2
      platform: linux/amd64
      triplet: multiarch-android-unknown
      makecmd: libs android
      prepcmd: bash install-sdk.sh
      flutter: flutter
      debian_arch: na
      flutter_arch: na
    - image: git.mrcyjanek.net/mrcyjanek/flutter:linux
      platform: linux/amd64
      triplet: x86_64-linux-gnu
      makecmd: linux deb
      prepcmd: echo ok
      flutter: flutter
      debian_arch: amd64
      flutter_arch: x64
    - image: git.mrcyjanek.net/mrcyjanek/flutter:linux
      platform: linux/aarch64
      triplet: aarch64-linux-gnu
      makecmd: linux deb
      prepcmd: echo ok
      flutter: flutter
      debian_arch: arm64
      flutter_arch: arm64
    - image: git.mrcyjanek.net/mrcyjanek/sailfishos:4.5.0.18_aarch64
      platform: linux/aarch64
      triplet: aarch64-linux-sailfishos
      makecmd: sailfishos
      prepcmd: bash elinux/sailfish_prepare.sh && source $HOME/.bashrc
      flutter: flutter-elinux
      debian_arch: arm64
      flutter_arch: arm64


labels:
  platform: ${platform}
steps:
  - name: Build package
    image: ${image}
    environment:
      - ANDROID_HOME=/root/.cache/android_sdk
      - ANDROID_SDK_ROOT=/root/.cache/android_sdk
    commands:
      - ${prepcmd}
      - export PATH="$${ANDROID_HOME}/cmdline-tools/latest/bin:$${ANDROID_HOME}/platform-tools:$${ANDROID_HOME}/emulator:$${PATH}"
      - git config --global --add safe.directory $PWD
      - git fetch
      - ${flutter} pub get
      - ${flutter} pub get # yes we need it twice
      - make version
      - TARGET_TRIPLET=${triplet} FLUTTER_ARCH=${flutter_arch} DEBIAN_ARCH=${debian_arch} make ${makecmd}
    volumes:
      - /opt/cache/${triplet}/dotcache:/root/.cache
      - /opt/cache/${triplet}/dotgradle:/root/.gradle
      - /opt/cache/${triplet}/dotpub-cache:/root/.pub-cache
  - name: Publish release
    image: git.mrcyjanek.net/mrcyjanek/debian:bookworm
    commands:
      - rm -rf ~/.ssh || true
      - mkdir -p ~/.ssh
      - echo "$${SSH_PRIVKEY}" > ~/.ssh/id_rsa
      - chmod 700 ~/.ssh
      - chmod 600 ~/.ssh/id_rsa
      - rsync --mkpath -e "ssh -o StrictHostKeyChecking=no" -raz build/linux/*/release/debian/*.deb $${SSH_HOST}:"$${SSH_BASE_PATH}/$(git describe --tags)/$${triplet}/xmruw.deb" || true
      - curl --user mrcyjanek:$${PAT_SECRET_PACKAGE} --upload-file build/linux/*/release/debian/*.deb https://git.mrcyjanek.net/api/packages/mrcyjanek/debian/pool/no-distro/main/upload || true
      - rsync --mkpath -e "ssh -o StrictHostKeyChecking=no" -raz build/linux/*/release/*.tar.xz $${SSH_HOST}:"$${SSH_BASE_PATH}/$(git describe --tags)/$${triplet}/xmruw.tar.xz" || true
      - rsync --mkpath -e "ssh -o StrictHostKeyChecking=no" -raz build/elinux/*/release/*.rpm $${SSH_HOST}:"$${SSH_BASE_PATH}/$(git describe --tags)/$${triplet}/" || true
      - rsync --mkpath -e "ssh -o StrictHostKeyChecking=no" -raz build/app/outputs/flutter-apk/*-x86_64-*.apk $${SSH_HOST}:"$${SSH_BASE_PATH}/$(git describe --tags)/x86_64-linux-android/" || true
      - rsync --mkpath -e "ssh -o StrictHostKeyChecking=no" -raz build/app/outputs/flutter-apk/*-arm64-v8a-*.apk $${SSH_HOST}:"$${SSH_BASE_PATH}/$(git describe --tags)/aarch64-linux-android/" || true
      - rsync --mkpath -e "ssh -o StrictHostKeyChecking=no" -raz build/app/outputs/flutter-apk/*-armeabi-v7a-*.apk $${SSH_HOST}:"$${SSH_BASE_PATH}/$(git describe --tags)/armv7a-linux-androideabi/" || true
    secrets: [ ssh_privkey, ssh_host, ssh_base_path, pat_secret_package ]