name: Build xmruw
run-name: Building xmruw for supported targets
on: [push]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Flutter pub get
        run: |
          flutter pub get
      - name: Build changelog
        run: ./build_changelog.sh
      - name: make version
        run: |
          make version
      - name: Build apk
        run: |
          make libs_android_download
          wget https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz -O /tmp/upx.tar.xz
          unxz /tmp/upx.tar.xz
          (cd /tmp && tar xvf /tmp/upx.tar)
          for i in android/app/src/main/jniLibs/*/*.so;
          do
            /tmp/upx-4.2.4-amd64_linux/upx --android-shlib --all-methods --all-filters "$i" &
          done
          wait
          make android
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/*.apk
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android monero ${{ matrix.stealth }}
          path: build/app/outputs/flutter-apk/*.apk
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build libgtk-3-dev
      - name: Flutter pub get
        run: |
          flutter pub get
      - name: Build changelog
        run: ./build_changelog.sh
      - name: make version
        run: |
          make version
      - name: Build .tar.gz
        run: |
          make linux FLUTTER_ARCH=x64
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/linux/*/release/*.tar.xz
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux monero ${{ matrix.stealth }}
          path: build/linux/*/release/*.tar.xz
  macos:
    strategy:
      matrix:
        stealth: [LIBSTEALTH_DISABLED]
      fail-fast: false
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: macos-ccache
      - name: install dependencies
        run: |
          brew install ccache unbound boost@1.76 zmq autoconf automake libtool && brew link boost@1.76
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: install dependencies
        run: |
          brew install create-dmg
      - name: Flutter pub get
        run: |
          flutter pub get
      - name: Build changelog
        run: ./build_changelog.sh
      - name: make version
        run: |
          make version_nongnu
      - name: Build .tar.gz
        run: |
          make macos_arm64
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/linux/*/release/*.tar.xz
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: darwin monero ${{ matrix.stealth }}
          path: build/*darwin_*.dmg
  sailfishos:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: build
        run: |
          cd $GITHUB_WORKSPACE
          docker run --rm -v $PWD:$PWD -w $PWD ghcr.io/mrcyjanek/sailfishos:4.6.0.11_target_aarch64 bash -c './elinux/sailfish_prepare.sh && source $HOME/.bashrc && ./build_changelog.sh && make version && ./elinux/sailfish_build.sh'
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/elinux/*/release/unnamed-*-wallet.*.rpm
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sfos monero ${{ matrix.stealth }}
          path: build/elinux/*/release/unnamed-*-wallet.*.rpm
  windows:
    strategy:
      matrix:
        stealth: [LIBSTEALTH_DISABLED]
    name: windows build
    runs-on: windows-latest
    steps:
      - name: Checkout unnamed_monero_wallet repo
        uses: actions/checkout@v4
        with:
          repository: MrCyjaneK/unnamed_monero_wallet
          fetch-depth: 0
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: git make xz autotools mingw-w64-x86_64-gcc mingw-w64-x86_64-jq
      - name: ./build_changelog.sh
        run: ./build_changelog.sh
        shell: msys2 {0}
        continue-on-error: true
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
      - name: Flutter pub get
        run: |
          flutter pub get
      - name: licenses [dummy]
        run: dart run flutter_oss_licenses:generate -o lib/helpers/licenses.g.dart
      - name: make version
        run: make version
        shell: msys2 {0}
      - name: build
        run: flutter build windows
        continue-on-error: true
      - name: make windows_libs_download
        run: make windows_libs_download
        shell: msys2 {0}
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: xmruw-windows-x86_64.zip
          directory: build/windows/x64/runner/Release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/windows/x64/runner/Release/xmruw-windows-x86_64.zip
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows monero ${{ matrix.stealth }}
          path: build/windows/x64/runner/Release/xmruw-windows-x86_64.zip

