name: Build xmruw
run-name: Building xmruw for supported targets
on: [push]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Flutter pub get
        run: |
          flutter pub get
      - name: make version
        run: |
          make version
      - name: Build apk
        run: |
          make libs_android_download
          make android
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/*.apk
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build libgtk-3-dev
      - name: Flutter pub get
        run: |
          flutter pub get
      - name: make version
        run: |
          make version
      - name: Build .tar.gz
        run: |
          make linux FLUTTER_ARCH=x64
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/linux/x64/release/xmruw-linux-x64.tar.xz
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
  sailfishos:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mrcyjanek/sailfishos:4.6.0.11_target_i486
    steps:
      - name: prepare os
        run: |
          zypper in -y ffmpeg-tools git clang libxkbcommon-devel wayland-protocols-devel wayland-client wayland-egl-devel make glibc-static
          touch ~/.profile
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          source ~/.profile
          nvm install 20
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build libgtk-3-dev
      - name: Flutter pub get
        run: |
          flutter pub get
      - name: make version
        run: |
          make version
      - name: Build .tar.gz
        run: |
          make linux FLUTTER_ARCH=x64
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/linux/x64/release/xmruw-linux-x64.tar.xz
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}