name: Build xmruw
run-name: Building xmruw for supported targets
on: [push]
jobs:
  android:
    strategy:
      matrix:
        coin: [COIN_MONERO, COIN_WOWNERO]
        stealth: [LIBSTEALTH_CALCULATOR, LIBSTEALTH_DISABLED]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Codegen
        run: ./codegen.sh -D${{ matrix.coin }} -D${{ matrix.stealth }}
      - name: Flutter pub get
        run: |
          flutter pub get
      - name: make version
        run: |
          make version
      - name: Build apk
        run: |
          make libs_android_download
          make android
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/*.apk
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android ${{ matrix.coin }} ${{ matrix.stealth }}
          path: build/app/outputs/flutter-apk/*.apk
  linux:
    strategy:
      matrix:
        coin: [COIN_MONERO, COIN_WOWNERO]
        stealth: [LIBSTEALTH_CALCULATOR, LIBSTEALTH_DISABLED]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build libgtk-3-dev
      - name: Codegen
        run: ./codegen.sh -D${{ matrix.coin }} -D${{ matrix.stealth }}
      - name: Flutter pub get
        run: |
          flutter pub get
      - name: make version
        run: |
          make version
      - name: Build .tar.gz
        run: |
          make linux FLUTTER_ARCH=x64
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/linux/*/release/*.tar.xz
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux ${{ matrix.coin }} ${{ matrix.stealth }}
          path: build/linux/*/release/*.tar.xz
  sailfishos:
    strategy:
      matrix:
        coin: [COIN_MONERO, COIN_WOWNERO]
        stealth: [LIBSTEALTH_CALCULATOR, LIBSTEALTH_DISABLED]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Codegen
        run: ./codegen.sh -D${{ matrix.coin }} -D${{ matrix.stealth }}
      - name: build
        run: |
          cd $GITHUB_WORKSPACE
          docker run --rm -v $PWD:$PWD -w $PWD ghcr.io/mrcyjanek/sailfishos:4.6.0.11_target_aarch64 bash -c './elinux/sailfish_prepare.sh && source $HOME/.bashrc && ./build_changelog.sh && make version && ./elinux/sailfish_build.sh'
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/elinux/*/release/unnamed-monero-wallet.*.rpm
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sfos ${{ matrix.coin }} ${{ matrix.stealth }}
          path: build/elinux/*/release/unnamed-*-wallet.*.rpm