name: Android Release
run-name: Building xmruw for android
on: 
  push:
    tags:
      - '*'

jobs:
  android-apk-release:
    runs-on: androidsdk-flutter
    steps:
      # - name: Prepare F-droid repo
      #   run: |
      #     mkdir /fdroidrepo \
      #     && fdroid init
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Flutter pub get
        run: |
          cd ${{ gitea.workspace }} \
          && flutter pub get
      - name: make version
        run: |
          cd ${{ gitea.workspace }} \
          && make version
      - name: Build apk
        continue-on-error: false
        run: |
          cd ${{ gitea.workspace }} \
          && make apk
      # - name: Build linux (debian)
      #   continue-on-error: true
      #   run: |
      #     cd ${{ gitea.workspace }} \
      #     && make deb \
      #     && curl --user mrcyjanek:$PAT_SECRET_PACKAGE \
      #     --upload-file build/linux/x64/release/debian/*.deb \
      #     https://git.mrcyjanek.net/api/packages/mrcyjanek/debian/pool/no-distro/main/upload
      - name: Build linux (tarball)
        continue-on-error: true
        run: |
          cd ${{ gitea.workspace }} \
          && make linux
      - name: Create release
        uses: akkuman/gitea-release-action@v1
        with:
          body: |
            This is a **preview** release to be used by testers.
            It was build from **${{ gitea.ref }}** commit `${{ gitea.sha }}`

            Please note that this app is being signed by a public private key in the release tab. Use f-droid repository for a secure download.

            - `app-calc-release.apk` is the stealth mode version of the app [Wiki](https://git.mrcyjanek.net/mrcyjanek/unnamed_monero_wallet/wiki/Stealth-Mode-%28calculator%29)
            - `app-clean-release.apk` is the normal, clean xmruw

            ### Release info
            ${{ github.event.head_commit.message }}
          #name: "${{ gitea.reg_name }}-${{ gitea.sha }}"
          #tagname: "${{ gitea.reg_name }}-${{ gitea.sha }}"
          files: |-
            ${{ gitea.workspace }}/build/app/outputs/flutter-apk/app-calc-release.apk
            ${{ gitea.workspace }}/build/app/outputs/flutter-apk/app-clean-release.apk
            ${{ gitea.workspace }}/build/linux/x64/release/xmruw-linux-amd64.tar.xz